### ISSUE TITLE
error running tracrr with eclipse nodeclipse

### ISSUE THREAD

**Issue by rapiddata** [doublerebel/tracrr#1]
in eclipse debug configuration for I entered the following for node arguments:
--expose-debug-as <name>

this is what i see in the console window
node --debug-brk=5858 --expose-debug-as <name> C:\Users\lc8341\workspace\node-demo\app-separate-files.js --expose-debug-as <name> 
node --debug-brk=5858 C:\Users\lc8341\workspace\node-demo\app-separate-files.js --expose-debug-as <name> 
node --debug-brk=5858 --expose-debug-as <name> C:\Users\lc8341\workspace\node-demo\app-separate-files.js 

getting the following error
Error: missing value for flag --expose-debug-as of type string
Try --help for options

module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Users\lc8341\workspace\node-demo<name>'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

here is app.js
var Tracrr = require("./tracrr-master/lib/tracrr");
Tracrr.logTo(console);

**Comment by doublerebel** [comment]
Sorry, my documention should be more explicit.   The `--expose-debug-as` flag takes a string for the name of the global object to attach Debug property.  **traccr** [uses `debug` by default](https://github.com/doublerebel/tracrr/blob/master/src/tracrr.coffee#L23).  So you would probably want:
 `node --debug-brk=5858 --expose-debug-as debug C:\Users\lc8341\workspace\node-demo\app-separate-files.js`

But, I haven't used this module in a while, so let me know if that doesn't work!

**Comment by rapiddata** [comment]
I tried that an now I am getting the following error with eclipse/nodeclipse plugin
Nodeclipse/chromedevtools failed to connect to Standalone V8 VM ( Check Help (F1) and Support http://www.nodeclipse.org/#support )
. Info:
Failed to get version

**Comment by doublerebel** [comment]
I've never used the nodeclipse plugin, it's possible that the settings aren't compatible.  Can you try it with standalone node-inspector and see if that works?
